// Generated by CoffeeScript 1.4.0
(function() {
  var config, file, fs, jsfile, _i, _len, _ref;

  config = {
    third_party: require(__dirname + '/../config/third_party.json')
  };

  fs = require('fs');

  jsfile = '';

  _ref = config.third_party.js;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    file = _ref[_i];
    jsfile += fs.readFileSync(__dirname + '/../' + config.third_party.path + file, {
      encoding: 'utf-8'
    });
  }

  exports.js = function(req, res) {
    return res.end(jsfile);
  };

  exports.css = function(req, res) {
    return res.end('');
  };

}).call(this);
